### PR TITLE
Tinymce fix notifications

### LINKED ISSUE #245: Unable to update the body of a notification in the Status application.
https://library.tamu.edu/status/management/notifications

Image

### PR DESCRIPTION
**Pull request by wwelling**
# Description

Two things; one the tinymce wysiwyg was not receiving the notification data on update. This is inconsistent with expected use and unknown cause with the tamu-library-component. Adding timeout to digest cycle and reserving the binding with notification data from the scope to the modal resolved this issue.

Until tl-wysiwyg affords consistent binding here is the workaround:

```
            const modal = angular.element('#editNotificationModal');
            if (modal) {
                const iframe = modal.find("iframe");
                if (iframe && iframe.length >= 1) {
                    iframe[0].contentDocument.body.innerHTML = notification.body;
                }
            }
```            

Fixes #245 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Test locally with various notifications created and modified.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: app/controllers/notificationController.js [hunk 1]
```diff
@@ -27,24 +27,27 @@ app.controller('NotificationController', function ($controller, $scope, Notifica
 
     $scope.forms = {};
 
-    $scope.notificationToDelete = {};
+    var emptyNotification = {
```
Comment (kaladay) [inline app/controllers/notificationController.js:30]:
```suggestion
    const emptyNotification = {
```

I suggest using `const` whenever reasonable and possible.
I don't see `emptyNotification` being re-assigned anywhere.

File: tests/unit/controllers/notificationControllerTest.js [hunk 2]
```diff
@@ -72,13 +73,14 @@ describe('controller: NotificationController', function () {
 
     describe('Are the scope methods working as expected', function () {
         it('resetNotifications should reset notifications', function () {
-            var notification;
-            scope.notificationData = null;
+            var notification = new Notification();
```
Comment (kaladay) [inline tests/unit/controllers/notificationControllerTest.js:76]:
```suggestion
            const notification = new Notification();
```
Possible improvement.
I don't know if we should change this or not since.
It is convenient to change because the line is being changed anyway.

However, The rest of the file uses `var` in similar ways so changing this in isolation would be inconsistent.

Feel free to ignore this request if you feel following consistency to be important here.

Updating the other similar cases is also an option.

**Review by kaladay — CHANGES_REQUESTED** [review]

File: app/controllers/notificationController.js (hunk 1 above)
Comment (wwelling) [reply app/controllers/notificationController.js:30]: I left it as var for consistency. Refactoring for later ECMA version is scope creep.

https://github.com/search?q=repo%3ATAMULib%2FLibraryServiceStatusSystemUI%20var&type=code
https://github.com/search?q=repo%3ATAMULib%2FLibraryServiceStatusSystemUI+const&type=code

File: tests/unit/controllers/notificationControllerTest.js (hunk 2 above)
Comment (wwelling) [reply tests/unit/controllers/notificationControllerTest.js:76]: Again. Same here. Refactoring var to const should be a dedicated task for code maintenance which applies a linting rule and such. I still consider this scope creep regardless of maybe consistency rule doesn't apply to new code.

File: app/controllers/notificationController.js (hunk 1 above)
Comment (kaladay) [reply app/controllers/notificationController.js:30]: There is this one:
- https://github.com/TAMULib/LibraryServiceStatusSystemUI/blob/2809f72219d3f014cd6b543b9cff4718d0563172/app/controllers/notificationController.js#L68


But I am fine with going forward as it is AngularJS (aka old).

**Review by kaladay — APPROVED** [review]
Approved on the basis that `var` is being used to be consistent with existing code.
